### PR TITLE
Re-factor of gem to allow multiple defined domains.

### PR DESCRIPTION
**Pull request by xsrust**
# Multi-Domain
## New Features
- Adds the ability to support multiple translation domains, synced to multiple Translation.io projects.
- This allows different sub-sections of your application to be split off into projects for different translators.  Our use-case, an open source project, leads us to desire a main translation repository for the group as a whole, with separate repositories for the differing content of the contributing organisations.
- Translations fall-through, first searching the first defined domain, and then others

## Implimentation
The additions here should not affect the usage/configuration of any current users, and only expand the functionality

## Config Changes:
The multiple domains can be defined in a configuration hash, with attributes defined for each.
The domain with the folders: [] will be classed the default domain, and will exclude the folders defined for other domains.
The first defined domain is also the first to be looked up for translation, therefore any other translations in later defined domains will not be found.  A potential refactor/improvement would be to exclude the keys from this domain from being used in the others, or to adjust your ordering accordingly with the current implementation.
Below is an example config hash:
```
config.domains = [{
      name: 'app',
      api_key: ENV['TRANSLATION_API_APP'],
      source_locale: 'en',
      target_locales: ['de', 'en-GB', 'en-US', 'es', 'fr-FR', 'fi', 'sv-FI', 'pt-BR'],
      folders: []
    },
    {
      name: 'client-domain',
      api_key: ENV['TRANSLATION_API_CLIENT'],
      source_locale: 'en',
      target_locales: ['fi', 'sv-FI'],
      folders: ['app/views/branded/']
    }
  ]
```
If no `config.domains` is specified, config falls through to the previous formatting.

## Rake tasks
Added a flag to the rake-tasks to specify which domain(s) to run the task over.
ex: 
`rake translation:<task> -- -d app`
`rake translation:<task> -- --domain=app,client`
With no arguments specified, it will default to run over all available domains
Without a multi-domain configuration, these arguments cannot be used

### CODE REVIEW

**Comment by MichaelHoste** [comment]
Hi @xsrust,

I started to work on this pull request and the more I worked on it and the more if felt "wrong".

My issue here is that the new `domains` variable doesn't duplicate the whole configuration, but just part of it (`api_key`, `name`, `source_locale`, `target_locales` and `folders`).

I had another issue with YAML files. A lot of rails projects have many YAML files and with your solution, they would be synchronized in both your translation.io projects.

A better way to achieve what you want to do would be to create a `translation.rb` file like this:

```ruby
if !ENV['DOMAIN'] || ENV['DOMAIN'] == 'app'
  TranslationIO.configure do |config|
    config.api_key              = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
    config.source_locale        = 'en'
    config.target_locales       = ['de', 'en-GB', 'en-US', 'es', 'fr-FR', 'fi', 'sv-FI', 'pt-BR']
    config.text_domain          = 'app'
    config.bound_text_domains   = ['app', 'client']
    config.ignored_source_paths = ['app/views/branded/']
  end
elsif ENV['DOMAIN'] == 'client'
  TranslationIO.configure do |config|
    config.api_key              = 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
    config.source_locale        = 'en'
    config.target_locales       = ['fi', 'sv-FI']
    config.text_domain          = 'client'
    config.ignored_source_paths = Dir.glob('**/*').select { |f| File.directory? f }.collect { |name| "#{name}/" } - ['app/', 'app/views/', 'app/views/branded/']
    config.disable_yaml         = true
  end
end
```

you can synchronize with:

 * `DOMAIN='app' bundle exec rake translation:sync`
 * `DOMAIN='client' bundle exec rake translation:sync`

And make sure to start your app with:

 * `bundle exec rails s` (to use both domains thanks to `bound_text_domains`).

And the best of it: no need to add complexity to this gem (except `text_domain`, `bound_text_domain` and `disable_yaml ` but that's useful anyway).

What do you think about it?

**Comment by MichaelHoste** [comment]
I @xsrust , I don't know if you noticed but the last gem version has these extra options  (`config.disable_yaml`, `config.text_domain` and `config.binded_text_domains`) and they may help you with multi-domains as explained above.

=> https://github.com/translation/rails/releases/tag/v1.18

I'll close this pull request since I think it solves that specific issue but with a different approach.

**Comment by xsrust** [comment]
Hi @MichaelHoste 
My appoligies for the radio-silence, I've finally freed-up to work some more on this.
I agree that this is a much cleaner/less disruptive implimentation of the feature-set which I required.  Thank you for taking the time to refactor this work into your codebase.

I have implimented according to your suggestions, and I ran into a couple of potential issues with the way the `config.ignored_source_paths`, in tandem with `config.source_files_for_formats()` filter files.

The first is that I can't specify a nested folder without specifying all of it's ancestors (i.e., to ignore everything except the `app/views/branded` folder, I will also need to keep the `app` and `app/views` folders.  This is because of the way in which file-exclusion process is working: https://github.com/translation/rails/blob/99236a9875e136707fd89a1f557d7b875a33ecca/lib/translation_io/config.rb#L147-L149  Here, if the file's path starts_with any of the excluded folders, the file is removed.  This need to specify parent-folders as included has the side-effect that if there are files in any of those parent folders which have been included, these files will also be included in the translation.  Fortunately, I dont seem to have any files in those directories, just folders, but I could see somebody else coming across this problem.

The seccond, is that I cannot currently say that I'd like this domain to apply to `app/views/branded/*`, and have it apply to all sub-folders of that folder.  Instead, any sub-folders have to be specified manually.  This can be done, but it feels like there should be an easier solution here.  

That being said, neither of those blocks me from using the service the way I originally wanted to.
Thanks again for considering my feature and refactoring the work into your gem.

**Comment by MichaelHoste** [comment]
Hi @xsrust,

I refactored `source_files_for_formats` to speed up the process and make it more logical. I hope it will also solve your issues: https://github.com/translation/rails/commit/ffb1ae086903199ffac6a867f083a3e63eb21632

If not, don't forget that you can customise the expected behaviour with some code like:

```
 config.ignored_source_paths = Dir["./**/*.{rb,erb}"].reject { |f| f.include?('app/views/branded') }
```

**Pull request closed without merging**
