### PR TITLE
Load translations from specified gems

### PR DESCRIPTION
**Pull request by erictuvesson**

### CODE REVIEW

**Comment by MichaelHoste** [comment]
Hi @erictuvesson,

Thanks for this pull request!

I'm not sure to understand it correctly. Do you want to allow parsing of GetText strings from external gems? I'm curious, what gems do you know that use the GetText syntax?

**Comment by erictuvesson** [comment]
Hi @MichaelHoste,

Our internal gems currently use GetText strings :stuck_out_tongue_closed_eyes: I know it's not the most optimal solution, however it's a fast solution and works for us.

I noticed that https://github.com/translation/rails/pull/27 PR calls it ```forced_source_paths``` and doesn't have anything to do with the gems, it would be a cleaner solution instead of this.

**Comment by MichaelHoste** [comment]
Thanks for your feedback @erictuvesson.

It makes sense for your internal gems! I'll merge #27 next week because I need to make sure it doesn't break anything since it's a big structural change. If it can solve your issue at the same time, it would be great!

**Comment by MichaelHoste** [comment]
Hi @erictuvesson,

I added your pull-request into the master branch. It's not exactly the same but it will work as expected.
See: https://github.com/translation/rails#gems-with-gettext-strings

Thanks for your suggestion!

I'll close this pull request, feel free to reopen it if you have something to add. A new version of the gem will be released soon with these changes.

**Pull request closed without merging**
